version: "3.9"
services:
  es01:
    # image: "docker.elastic.co/elasticsearch/elasticsearch:8.1.0"
    build: 
      context: ./
      dockerfile: elasticsearch-dockerfile
    container_name: es01
    network_mode: "elastic"
    # networks:
    #   - "elastic"
    ports:
      - "9200:9200"
      - "9300:9300"
    # volumes:
    #   - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    #   - ./instance.yml:/usr/share/elasticsearch/config/instance.yml
    environment:
      ES_JAVA_OPTS: '-Xms750m -Xmx750m'
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: elastic
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      http.cors.enabled: 'true'
      http.cors.allow-origin: '*'

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:6.6.1
  #   ports:
  #     - "5044:5044"
  #     - "9600:9600"
  #   configs:
  #     - source: logstash_config
  #       target: /usr/share/logstash/config/logstash.yml:rw
  #     - source: logstash_pipeline
  #       target: /usr/share/logstash/pipeline/logstash.conf
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     xpack.monitoring.elasticsearch.url: "elasticsearch:9200"
  #     xpack.monitoring.elasticsearch.username: "elastic"
  #     xpack.monitoring.elasticsearch.password: "MyPw123"
  #   networks:
  #     - elk
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.6.1
  #   ports:
  #     - "5601:5601"
  #   configs:
  #     - source: kibana_config
  #       target: /usr/share/kibana/config/kibana.yml
  #   networks:
  #     - elk
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  # configs:
  #   elastic_config:
  #     file: ./elasticsearch/config/elasticsearch.yml
  #   logstash_config:
  #     file: ./logstash/config/logstash.yml
  #   logstash_pipeline:
  #     file: ./logstash/pipeline/logstash.conf
  #   kibana_config:
  #     file: ./kibana/config/kibana.yml
