version: "3.9"
services:
  kibana01:
    # image: docker.elastic.co/kibana/kibana:8.0.1
    build: 
      context: ./
      dockerfile: kibana-dockerfile
    container_name: kibana01
    network_mode: "elastic"
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: '["http://172.19.0.2:9200"]'
      ELASTIC_PASSWORD: elastic
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: "AdKtaoNka6NSD0Q652gI"
      # XPACK_MONITORING_ENABLED: "true"
      # XPACK_MONITORING_COLLECTION_ENABLED: "true"
      XPACK_SECURITY_ENABLED: "true"
